class GroupException(Exception):
    pass


class HumanException(Exception):
    pass
